name: APM Android newarch dev sync
on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev-newarch
      - run: |
          git config --global user.email 106490582+lovegaoshi@users.noreply.github.com
          git config --global user.name lovegaoshi

      - name: Get Recent Commit Tag
        id: get_commit_tag
        run: |
          COMMIT_TAG=$(git describe --tags --abbrev=0)
          echo "COMMIT_TAG=${COMMIT_TAG}" >> $GITHUB_ENV

      - name: Display Commit Tag
        run: |
          echo "Commit Tag: $COMMIT_TAG"
