name: APM Android newarch dev sync
on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev-newarch

      - name: commit
        run: |
          git config pull.rebase false
          git pull origin dev --allow-unrelated-histories
          git config --global user.email 106490582+lovegaoshi@users.noreply.github.com
          git config --global user.name lovegaoshi
          git commit -m "chore: dev sync" -a

      - name: Push changes to dev-newarch
        uses: ad-m/github-push-action@master
        with:
          tags: true
          branch: dev-newarch
