name: APM Android newarch dev sync
on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev-newarch
      - run: |
          cd /home/runner/work/azusa-player-mobile/azusa-player-mobile
          git config --global user.email 106490582+lovegaoshi@users.noreply.github.com
          git config --global user.name lovegaoshi
          git config pull.rebase true
          git pull origin dev
          git commit -m "chore: dev sync" -a
          git push
