name: APM Test Suite
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  jest:
    runs-on: ubuntu-latest
    name: APM tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 10
          command: yarn

      - name: run tests
        run: |
          git submodule update --init --recursive
          yarn test
